### ISSUE TITLE
Sequelize 사용시 Nest dependency 문제

### ISSUE THREAD

**Issue by Hwan-seok** [Hwan-seok/word-chain-nest#4]
## 문제
- [공식 문서](https://docs.nestjs.com/recipes/sql-sequelize) 참고하여 다음 코드와 같이 `sequelize`의 `WORD_REPOSITORY`를 주입하였는데, 다음과 같은 에러 발생

> word.entitiy.ts
```ts
import { Table, Column, Model, PrimaryKey } from 'sequelize-typescript';

@Table
export class Word extends Model<Word> {
  @PrimaryKey
  @Column
  id: number;

  @Column
  word: string;

  @Column
  part: string;
}

```
> word.module.ts
```ts
import { Module } from '@nestjs/common';
import { WordService } from './word.service';
import { wordsProviders } from './word.providers';
import { DatabaseModule } from '../database/database.module';
@Module({
  imports: [DatabaseModule],
  providers: [WordService, ...wordsProviders],
  exports: [WordService],
})
export class WordModule {}

```
> word.providers.ts
```ts
import { Word } from './word.entity';

export const wordsProviders = [
  {
    provide: 'WORDS_REPOSITORY',
    useValue: Word,
  },
];

```
> word.service.ts
```ts
import { Injectable, Inject } from '@nestjs/common';
import { Word } from './word.entity';

@Injectable()
export class WordService {
  constructor(
    @Inject('WORD_REPOSITORY') private readonly WORD_REPOSITORY: typeof Word,
  ) {}
  async findOne(): Promise<Word> {
    return await this.WORD_REPOSITORY.findOne<Word>();
  }
}
```
```ts
[ExceptionHandler] Nest can't resolve dependencies of the WordService (?). Please make sure that the argument at index [0] is available in the WordModule context. +8ms
Error: Nest can't resolve dependencies of the WordService (?). Please make sure that the argument at index [0] is available in the WordModule context.
    at Injector.lookupComponentInExports (C:\Users\hwanseok.kang\Desktop\lining\node_modules\@nestjs\core\injector\injector.js:183:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### 추정
- 다음 메서드를 클래스에서 제거해도 똑같이 디펜던시 에러 발생
```
  async findOne(): Promise<Word> {
    return await this.WORD_REPOSITORY.findOne<Word>();
  }
```

**Comment by Hwan-seok** [comment]
- Database connection 에는 문제가 없음

**Comment by Hwan-seok** [comment]
## 해결...
- `word.providers.ts` 에서는 `provide`를 `WORDS_REPOSITORY`로 줬는데, `word.service.ts`에서는 `WORD_REPOSITORY`로 `Inject` 해서 발생한 문제.. (오타)
